version: '3.7'

services:
  minimalism-service-jsonapi:
    container_name: minimalism-service-jsonapi
    image: carlonicora/php-cli-base:7.4.3.2
    working_dir: /app
    volumes:
      - ../:/app
      - ../:/opt/project
    tty: true
    stdin_open: true